### ISSUE TITLE
Дизайн админки пользователей

### ISSUE THREAD

**Issue by dyakovri** [profcomff/design#10]
### Подзадачи

- [x] profcomff/webapp-ui#147
- [x] profcomff/webapp-ui#144
- [x] profcomff/webapp-ui#145
- [x] profcomff/webapp-ui#146
